<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
            <div><p class="text-xs font-bold uppercase tracking-widest text-emerald-700">Fondasi administrasi</p><h2 class="mt-1 text-2xl font-semibold leading-tight text-gray-900">Sekretariat dan Master Data</h2><p class="mt-1 text-sm text-gray-500">Kelola data administrasi yang belum masuk ke modul operasional utama.</p></div>
            <a href="{{ route('dashboard') }}" class="text-sm font-semibold text-emerald-800">&larr; Dashboard</a>
        </div>
    </x-slot>
    <div class="dashboard-workspace min-h-screen px-0 py-8"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        @if(session('success'))<div class="dashboard-feedback dashboard-feedback--success">{{ session('success') }}</div>@endif
        <nav class="operations-tabs">@foreach($sections as $key => $label)<a href="{{ route('administration.foundation', ['section' => $key]) }}" @if($section === $key) aria-current="page" @endif>{{ $label }}</a>@endforeach</nav>

        @if($section === 'management')
            <section class="operations-panel"><div class="operations-panel__heading"><div><p class="eyebrow eyebrow--green">Periode</p><h3>Tambah periode kepengurusan</h3></div></div><form method="POST" action="{{ route('administration.foundation.store', 'management') }}" class="operations-form"><input type="hidden" name="record_type" value="period">@csrf<div class="operations-fields"><label>Nama periode<input name="name" placeholder="2026-2031" required></label><label>Mulai<input type="date" name="starts_at"></label><label>Selesai<input type="date" name="ends_at"></label><label>Status<select name="status"><option>Draft</option><option>Aktif</option><option>Arsip</option></select></label></div><div class="operations-form__actions"><button class="button button--primary">Simpan periode</button></div></form></section>
            <section class="operations-panel"><div class="operations-panel__heading"><div><p class="eyebrow eyebrow--green">Jabatan</p><h3>Tambah jabatan</h3></div></div><form method="POST" action="{{ route('administration.foundation.store', 'management') }}" class="operations-form"><input type="hidden" name="record_type" value="position">@csrf<div class="operations-fields"><label>Nama jabatan<input name="name" placeholder="Ketua" required></label><label>Urutan<input type="number" name="sort_order" min="0" value="0"></label></div><div class="operations-form__actions"><button class="button button--primary">Simpan jabatan</button></div></form></section>
            <section class="operations-panel"><div class="operations-panel__heading"><div><p class="eyebrow eyebrow--green">Anggota</p><h3>Tambah pengurus</h3></div></div><form method="POST" action="{{ route('administration.foundation.store', 'management') }}" class="operations-form"><input type="hidden" name="record_type" value="member">@csrf<div class="operations-fields"><label>Periode<select name="period_id" required>@foreach($periods as $period)<option value="{{ $period->id }}">{{ $period->name }}</option>@endforeach</select></label><label>Jabatan<select name="position_id"><option value="">Pilih jabatan</option>@foreach($positions as $position)<option value="{{ $position->id }}">{{ $position->name }}</option>@endforeach</select></label><label>Nama<input name="name" required></label><label>Gelar<input name="title"></label><label>Nomor HP<input name="phone"></label><label>Urutan<input type="number" name="sort_order" min="0" value="0"></label><label class="operations-field--wide">Alamat<input name="address"></label></div><div class="operations-form__actions"><button class="button button--primary">Simpan pengurus</button></div></form></section>
            <section class="operations-panel operations-panel--table"><div class="operations-panel__heading"><h3>Daftar pengurus</h3></div><div class="overflow-x-auto"><table class="operations-table"><thead><tr><th>Nama</th><th>Jabatan</th><th>Periode</th><th>Kontak</th></tr></thead><tbody>@forelse($members as $member)<tr><td>{{ $member->name }} {{ $member->title }}</td><td>{{ $member->position_name ?: '-' }}</td><td>{{ $periods->firstWhere('id', $member->period_id)?->name ?: '-' }}</td><td>{{ $member->phone ?: '-' }}</td></tr>@empty<tr><td colspan="4" class="operations-empty">Belum ada pengurus.</td></tr>@endforelse</tbody></table></div>{{ $members->links() }}</section>
        @else
            @php($formRoute = route('administration.foundation.store', $section))
            <section class="operations-panel"><div class="operations-panel__heading"><div><p class="eyebrow eyebrow--green">Input data</p><h3>{{ $sections[$section] }}</h3></div></div>
                <form method="POST" action="{{ $formRoute }}" class="operations-form">@csrf<div class="operations-fields">
                @if($section === 'documents')<label>Arah<select name="direction"><option>Masuk</option><option>Keluar</option></select></label><label>Nomor<input name="document_number"></label><label>Tanggal<input type="date" name="document_date" required></label><label>Pengirim<input name="sender"></label><label>Penerima<input name="recipient"></label><label>Perihal<input name="subject" required></label><label class="operations-field--wide">Catatan<textarea name="notes"></textarea></label>
                @elseif($section === 'proposals')<label>Nomor proposal<input name="proposal_number"></label><label>Tanggal<input type="date" name="proposal_date" required></label><label>Judul<input name="title" required></label><label>Tujuan<input name="recipient"></label><label>Nominal<input type="number" name="amount" min="0" step="1000"></label><label>Jenis<input name="proposal_type"></label><label class="operations-field--wide">Isi proposal<textarea name="content" rows="6"></textarea></label>
                @elseif($section === 'qurban-animals')<label>Tahun<input type="number" name="year" value="{{ now()->year }}" required></label><label>Jenis<select name="animal_type"><option>Sapi</option><option>Kambing</option></select></label><label>Pemilik<input name="owner_name" required></label><label>Peserta<input name="participant_name"></label><label>Alamat<input name="address"></label><label>Nomor HP<input name="phone"></label><label>Harga<input type="number" name="price" min="0"></label><label>Status pembayaran<select name="payment_status"><option>Belum Lunas</option><option>Lunas</option></select></label><label class="operations-field--wide">Catatan<textarea name="notes"></textarea></label>
                @elseif($section === 'qurban-distributions')<label>Tahun<input type="number" name="year" value="{{ now()->year }}" required></label><label>Tanggal<input type="date" name="distribution_date" required></label><label>Nama penerima<input name="recipient_name" required></label><label>Alamat<input name="address"></label><label>Jenis hewan<input name="animal_type"></label><label>Jumlah<input type="number" name="quantity" min="0" step="0.01" required></label><label class="operations-field--wide">Catatan<textarea name="notes"></textarea></label>
                @elseif($section === 'ramadan-donors')<label>Tahun<input type="number" name="year" value="{{ now()->year }}" required></label><label>Tanggal<input type="date" name="donation_date" required></label><label>Nama<input name="name" required></label><label>Alamat<input name="address"></label><label>Nominal<input type="number" name="amount" min="0" required></label><label>Jenis donasi<input name="donation_type" placeholder="Uang / makanan"></label><label class="operations-field--wide">Catatan<textarea name="notes"></textarea></label>
                @else<label>Tahun<input type="number" name="year" value="{{ now()->year }}" required></label><label>Tanggal<input type="date" name="collection_date" required></label><label>Jumlah<input type="number" name="amount" min="0" required></label><label class="operations-field--wide">Catatan<textarea name="notes"></textarea></label>@endif
                </div><div class="operations-form__actions"><button class="button button--primary">Simpan data</button></div></form>
            </section>
            <section class="operations-panel operations-panel--table"><div class="operations-panel__heading"><h3>Daftar tersimpan</h3></div><div class="overflow-x-auto"><table class="operations-table"><thead><tr><th>Tanggal/Tahun</th><th>Nama/Judul</th><th>Detail</th><th>Catatan</th></tr></thead><tbody>@forelse($records as $record)<tr><td>{{ $record->document_date ?? $record->proposal_date ?? $record->distribution_date ?? $record->donation_date ?? $record->collection_date ?? $record->year }}</td><td>{{ $record->subject ?? $record->title ?? $record->recipient_name ?? $record->name ?? $record->owner_name ?? '-' }}</td><td>{{ $record->direction ?? $record->proposal_number ?? $record->animal_type ?? ($record->amount ?? '-') }}</td><td>{{ $record->notes ?? $record->content ?? '-' }}</td></tr>@empty<tr><td colspan="4" class="operations-empty">Belum ada data.</td></tr>@endforelse</tbody></table></div>{{ $records->links() }}</section>
        @endif
    </div></div>
</x-app-layout>
